### ISSUE TITLE
Web 메뉴 내용 작성

### ISSUE THREAD

**Issue by highlaw00** [highlaw00/teamWebPage#12]
- 담당자: @hek-git 
- 브랜치 명: hek-git
- 개발 내용: Web 메뉴에 들어갈 블로그 작성
- 데드라인: 5월 29일
- 완료시 커멘트 작성 부탁드립니다.

**Comment by hek-git** [comment]
web 메뉴에 web, network와 관련된 블로그 올리고 pull request 올렸습니다!

**Comment by highlaw00** [comment]
확인하였습니다. hek-git 브랜치는 merge 이후 삭제하겠습니다.
