### ISSUE TITLE
Linux 메뉴 내용 작성

### ISSUE THREAD

**Issue by highlaw00** [highlaw00/teamWebPage#13]
- 담당자: @Serenata2 
- 브랜치 명: serenata2
- 개발 내용: Linux 메뉴에 들어갈 블로그 작성
- 데드라인: 5월 29일
- 완료시 커멘트 작성 부탁드립니다.

**Comment by Serenata2** [comment]
크게 OS 커널이란, Linux 명령어에 대한 2개의 블로그를 작성해 보았습니다.

**Comment by Serenata2** [comment]
기존에 "serenata2" branch에서 작업을 진행했는데, 작업 기간이 길어져서 "main" branch와 동기화가 잘 진행되지 못했습니다. 
이에, 새롭게 "main" branch에서 "serenata2_new" branch를 만들었고, 여기서 작업 후 main에 PR 요청을 보냈습니다.

**Comment by highlaw00** [comment]
확인했습니다. 그렇다면 serenata2 브랜치와 serenata2_new 브랜치 모두 작업이 끝난 것으로 확인하였고, 브랜치 삭제하겠습니다. 로컬에서도 삭제해주세요.

**Comment by Serenata2** [comment]
넵 알겠습니다
